# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: katamari_object.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15katamari_object.proto\x12\x0ekatamari_diary"\x91\x01\n\x0eKatamariObject\x12\x0c\n\x04name\x18\x01 \x01(\t\x12"\n\x04size\x18\x02 \x01(\x0e\x32\x14.katamari_diary.Size\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08location\x18\x04 \x01(\t\x12\x14\n\x0csize_to_roll\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t*\xde\x01\n\x04Size\x12\x0b\n\x07INVALID\x10\x00\x12\x10\n\x0cTHE_SMALLEST\x10\x01\x12\x13\n\x0f\x45XTREMELY_SMALL\x10\x02\x12\x0e\n\nVERY_SMALL\x10\x03\x12\t\n\x05SMALL\x10\x04\x12\x12\n\x0eSOMEWHAT_SMALL\x10\x05\x12\x0b\n\x07\x41VERAGE\x10\x06\x12\x11\n\rABOVE_AVERAGE\x10\x07\x12\x12\n\x0eSOMEWHAT_LARGE\x10\x08\x12\t\n\x05LARGE\x10\t\x12\x0e\n\nVERY_LARGE\x10\n\x12\x13\n\x0f\x45XTREMELY_LARGE\x10\x0b\x12\x0f\n\x0bTHE_LARGEST\x10\x0c'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "katamari_object_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _SIZE._serialized_start = 190
    _SIZE._serialized_end = 412
    _KATAMARIOBJECT._serialized_start = 42
    _KATAMARIOBJECT._serialized_end = 187
# @@protoc_insertion_point(module_scope)
